# Generated by Django 3.0.5 on 2020-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('condition', models.CharField(max_length=20)),
                ('master', models.CharField(max_length=20)),
                ('pqs', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('مقدماتی', 'مقدماتی'), ('متوسط', 'متوسط'), ('پیشرفته', 'پیشرفته'), ('فوق پیشرفته', 'فوق پیشرفته')], default='مقدماتی', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('trailer', models.TextField(default='')),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
