# Generated by Django 3.0.5 on 2020-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
