# Generated by Django 3.0.5 on 2020-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200414_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
