# Generated by Django 3.0.5 on 2020-04-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200415_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='master_des',
        ),
        migrations.RemoveField(
            model_name='course',
            name='master_img',
        ),
    ]
