# Generated by Django 3.0.5 on 2020-04-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('A', 'مقدماتی'), ('B', 'متوسط'), ('C', 'پیشرفته'), ('D', 'فوق پیشرفته')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
