# Generated by Django 3.0.5 on 2020-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200414_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
