# Generated by Django 3.0.5 on 2020-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200422_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='اسکوب', max_length=50),
        ),
    ]
