# Generated by Django 3.0.5 on 2020-04-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='existent',
        ),
    ]
