# Generated by Django 3.0.5 on 2020-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200422_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='pashmak'),
            preserve_default=False,
        ),
    ]
