# Generated by Django 3.0.5 on 2020-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
