# Generated by Django 3.0.5 on 2020-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200415_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='master_img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
